services:
  db:
    image: postgres:latest
    container_name: matchwave-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matchwave-app
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - SALT=${SALT}
      - SIGNING_KEY=${SIGNING_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrate

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - db
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://postgres:${DB_PASSWORD}@db:5432/postgres?sslmode=disable", "up"]
    volumes:
      - ./schema:/migrations

volumes:
  pgdata:
